//
//  Category.swift
//  AnimeManiac
//
//  Created by David-IOS on 09/01/2022.
//

import Foundation

struct Category {
    static let genre = [
        "action",
        "adventure",
        "comedy",
        "drama",
        "sci-fi",
        "space",
        "mystery",
        "magic",
        "supernatural",
        "police",
        "fantasy",
        "sports",
        "romance",
        "carsslice-of-life",
        "racing",
        "horror",
        "psychological",
        "thriller",
        "martial-arts",
        "super-power",
        "school",
        "ecchi",
        "vampire",
        "historical",
        "military",
        "dementia",
        "mecha",
        "demons",
        "samurai",
        "harem",
        "music",
        "parody",
        "shoujo-ai",
        "game",
        "shounen-ai",
        "kids",
        "hentai",
        "yuri",
        "yaoi",
        "anime-influenced",
        "gender-bender",
        "doujinshi",
        "mahou-shoujo",
        "mahou-shounen",
        "gore",
        "law",
        "cooking",
        "mature",
        "medical",
        "political",
        "tokusatsu",
        "youth",
        "workplace",
        "crime",
        "zombies",
        "documentary",
        "family",
        "food",
        "friendship",
        "tragedy",
        "isekai" ]
}
